# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true #3.0以后不支持
gems: [jekyll-paginate]

# Setup
title:               后山
tagline:             '有路'
description:         'Hieast的技术博客'
url:                 http://hieast.github.io
baseurl:             ''
paginate:            2

# About/contact
author:
  name:              Hieast
  url:               https://github.com/hieast
  email:             caisudong@foxmail.com

# Custom vars
version:             0.2.0
